//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacketDataIndexer.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Warning {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Warning() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacketDataIndexer.Resources.Warning", typeof(Warning).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при индексации данных в ElasticSearch: {0}.
        /// </summary>
        internal static string AnErrorOccuredWhileIndexing {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhileIndexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочитать AgentsReadDelay из файла конфигурации appsettings.json. Установлено значение &quot;10&quot;.
        /// </summary>
        internal static string FailedToReadAgentsReadDelay {
            get {
                return ResourceManager.GetString("FailedToReadAgentsReadDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочитать ClearTimeout из файла конфигурации. Установлено значение &quot;60&quot;.
        /// </summary>
        internal static string FailedToReadClearTimeout {
            get {
                return ResourceManager.GetString("FailedToReadClearTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочитать LastRedisValueIndex из файла конфигурации. Установлено значение &quot;0&quot;.
        /// </summary>
        internal static string FailedToReadLastRedisValueIndex {
            get {
                return ResourceManager.GetString("FailedToReadLastRedisValueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочитать MaxQueueSize из файла appsettings.json.
        /// </summary>
        internal static string FailedToReadMaxQueueSize {
            get {
                return ResourceManager.GetString("FailedToReadMaxQueueSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочитать StreamCount из файла конфигурации. Установлено значение &quot;500&quot;.
        /// </summary>
        internal static string FailedToReadStreamCount {
            get {
                return ResourceManager.GetString("FailedToReadStreamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочитать StreamReadDelay из файла appsettings.json. Установлено значение &quot;10&quot;.
        /// </summary>
        internal static string FailedToReadStreamReadDelay {
            get {
                return ResourceManager.GetString("FailedToReadStreamReadDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочитать StreamTTL из файла конфигурации. Установлено значение &quot;12&quot;.
        /// </summary>
        internal static string FailedToReadStreamTTL {
            get {
                return ResourceManager.GetString("FailedToReadStreamTTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить агентов. Вероятно, ни один из агентов не взаимодействует с Redis и его потоками. Проверьте работу службы на устройствах.
        /// </summary>
        internal static string NoAgentsWereFound {
            get {
                return ResourceManager.GetString("NoAgentsWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поток по ключу {0} пуст, ожидаются новые данные.
        /// </summary>
        internal static string StreamIsEmpty {
            get {
                return ResourceManager.GetString("StreamIsEmpty", resourceCulture);
            }
        }
    }
}
